#IF NEEDED, YOU CAN MODIFY THIS PROPERTY FILE
#ENSURE YOU ARE NOT CHANGING THE NAME OF THE PROPERTY
#YOU CAN CHANGE THE VALUE OF THE PROPERTY
#LOAD THE DETAILS OF USERNAME, PASSWORD AND DSN using this properties file only.

DB_USERNAME= ${sys:db_username}
DB_PASSWORD=${sys:db_password}
DSN =localhost/XE
PORT = 1521
ENCODING=UTF-8
