
#IF NEEDED, YOU CAN MODIFY THIS PROPERTY FILE
#ENSURE YOU ARE NOT CHANGING THE NAME OF THE PROPERTY
#YOU CAN CHANGE THE VALUE OF THE PROPERTY 
#LOAD THE DETAILS OF DSN,Port number, USERNAME AND PASSWORD using this properties file only. 
#Do not hard code the values in in any other files.

DB_USERNAME= system
DB_PASSWORD= 201002
DSN =localhost:1521/XEPDB1


